[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

[dev]
  command = "python app.py"
  port = 5000
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
