services:
  # A Docker web service - Updated for deployment
  - type: web
    name: serp-analyzer
    env: docker
    repo: https://github.com/philly88r/serp-analyzer.git
    branch: master
    dockerfilePath: ./Dockerfile
    dockerCommand: bash ./start.sh
    envVars:
      - key: PORT
        value: 8080
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /app/.playwright
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: PLAYWRIGHT_SKIP_VALIDATION
        value: "1"
    buildCommand: python -m playwright install chromium --with-deps && python -m playwright install-deps chromium
    healthCheckPath: /
    autoDeploy: true
