services:
  # A Docker web service - Updated for deployment
  - type: web
    name: serp-analyzer
    env: docker
    repo: https://github.com/philly88r/serp-analyzer.git
    branch: master
    dockerfilePath: ./Dockerfile
    dockerCommand: bash ./start.sh
    envVars:
      - key: PORT
        value: 8080
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /app/.playwright
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: PLAYWRIGHT_SKIP_VALIDATION
        value: "1"
      # Oxylabs Configuration
      - key: OXYLABS_USERNAME
        value: "customer-pematthews41_5eo28"
      - key: OXYLABS_PASSWORD
        value: "Yitbos88++88"
      - key: PROXY_URL
        value: "us-pr.oxylabs.io:10000"
      - key: SERP_API_URL
        value: "https://realtime.oxylabs.io/v1/queries/google/search"
      - key: PROXY_TYPE
        value: "residential"
      - key: COUNTRY
        value: "us"
      - key: GEMINI_API_KEY
        value: "AIzaSyBl6LgSol_l_ELLHhd5YX90VeXEwdt3xPU"
    buildCommand: python -m playwright install chromium --with-deps && python -m playwright install-deps chromium
    healthCheckPath: /
    autoDeploy: true
