services:
  # A Docker web service - Updated for deployment
  - type: web
    name: serp-analyzer
    env: docker
    region: ohio
    plan: free
    repo: https://github.com/philly88r/serp-analyzer.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8080
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.playwright
      - key: PLAYWRIGHT_CHROMIUM_ARGS
        value: --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage
      - key: RENDER_DISCOVERY_SERVICE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: PLAYWRIGHT_SKIP_VALIDATION
        value: "1"
      # Oxylabs Configuration
      - key: OXYLABS_USERNAME
        sync: false
      - key: OXYLABS_PASSWORD
        sync: false
      - key: PROXY_URL
        value: "us-pr.oxylabs.io:10000"
      - key: SERP_API_URL
        value: "https://realtime.oxylabs.io/v1/queries/google/search"
      - key: PROXY_TYPE
        value: "residential"
      - key: COUNTRY
        value: "us"
      - key: GEMINI_API_KEY
        sync: false
    buildCommand: python -m playwright install chromium && python -m playwright install-deps chromium
    healthCheckPath: /
    autoDeploy: true
