services:
  # A Docker web service
  - type: web
    name: serp-analyzer
    env: docker
    repo: https://github.com/philly88r/serp-analyzer.git
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: bash -c "python setup_playwright.py && gunicorn --bind 0.0.0.0:$PORT --timeout 300 app:app"
    envVars:
      - key: PORT
        value: 8080
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /app/.playwright
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: PLAYWRIGHT_SKIP_VALIDATION
        value: "1"
    buildCommand: python -m playwright install chromium --with-deps && python -m playwright install-deps chromium
    healthCheckPath: /
    autoDeploy: true
